spring:
  profiles:
     active:
     - dev
---

spring:
  profiles: dev
  application: 
     name:  microservicecloud-config-client
eureka:
  client:
     service-url:
       defaultZone: http://localhost:7001/eureka1     
---

spring:
  profiles: test
  application: 
     name:  microservicecloud-config-atguigu-client
eureka:
  client:
     service-url:
       defaultZone: http://localhost:7001/eureka12
